# Generated by Django 3.2.3 on 2021-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210529_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='', upload_to='posts/', verbose_name='Изображения'),
        ),
    ]
