# Generated by Django 3.2.3 on 2021-06-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(default=' ', upload_to='posts/', verbose_name='Изображения'),
        ),
    ]
